### ISSUE TITLE
Web Interface is Unbearably Slow

### ISSUE THREAD

**Issue by budpi** [mholgatem/ThermOS#10]
Not sure if it's the fact that i have 5 ds18b20's hooked up or what. But, ever since i updated the software it has been painfully slow...any ideas. 

Thanks!

**Comment by mholgatem** [comment]
I'm guessing that it probably is the number of sensors that you have. It is still running the same for me, even with the update. It does have to open and read each temp sensor file, which can be very slow if you are using a slow sd card. Make sure that you are using a class 10 card. Also, are you using wifi or ethernet? Running that many ds18b20's may be draining some of your power, I'll have to research it.

**Comment by mholgatem** [comment]
have you tried running it with just one sensor?

**Comment by budpi** [comment]
I am not using a class 10, i will remedy that when i can and then see if the issue persist. I am on Ethernet, i thought wifi dongle was the issue at first. I will try two or three sensors instead of five, getting an average of two or more rooms is the main selling point for me. Would there be a way to import temp data from one pi to another?

**Comment by mholgatem** [comment]
oh yeah, I'm not suggesting that you keep it at just one sensor. I'm just curious if it runs any faster with just one so that we can try and get this fixed. My guess would be that switching to a class 10 would give you the biggest gains, but there may be some things that we can change to get everything loading faster. I'm running the website through some audits and I think that there are some bits that I can trim here and there to speed things up.

**Comment by mholgatem** [comment]
yes, you probably could get it to read temp data from one pi to another via some type of serial communication, The easiest way would to be to rewrite the tempSensor.py file. It could do all of the reading and then just return what it finds.

**Comment by mholgatem** [comment]
I just had a thought. I remember you mentioning that you are running them kind of far through telephone wires, I wonder if they aren't getting enough juice. are you using the type that have resistor built in or did you add your own resistor?

**Comment by budpi** [comment]
I am using one 4.7k resistor as mentioned in the Adafruit Tutorial. I have used the wrong resistor before or hooked up a DS18B20 to a low quality wire or at too far a distance and the Serial Number was never populated in the correct format and didn't work. These sensors are working great and i was able to export the data to Ubidots awhile back but i figured that running the daemon and yours at the same time was slowing me down, i since then reflashed a new image and started over with just the ThermOS running. Same slow web interface results.

**Comment by budpi** [comment]
When i get home from work i will test the class10 sd card theory.

**Comment by mholgatem** [comment]
ok, sounds good. hopefully we can get you up and running

**Comment by budpi** [comment]
After new class 10 sd card flash and install...I am greeted with a "Welcome to nginx!" "

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx."

No Setup page.

**Comment by mholgatem** [comment]
sorry, I'm just in the middle of updating some stuff that should help speed up the web pages. For right now, you can just do this:

`apt-get remove nginx`

Then everything should work fine again

**Comment by mholgatem** [comment]
I have finished integrating nginx into the mix (there still may be some hiccups) but it should be quicker to run now. Do this, and you should be able to get up and running. Let me know how it goes:

```
cd ~
sudo rm -r ThermOS
git clone https://github.com/mholgatem/ThermOS 
cd ~/ThermOS  
sudo bash install.sh
```
