### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by roidimitris** [mholgatem/ThermOS#11]
Should the web interface function without the sensor connected? Cause I'm trying to check if it is working on my raspberry pi 3 but after the installation it does not find the webpage of the ip...

**Comment by mholgatem** [comment]
yes, it does work without a sensor connected, it will just display the error temp of -666.0°. Try running the webpage manually like this

```
sudo systemctl stop thermostat-web
cd ~/ThermOS
sudo python thermostat_web.py
```

It should tell you if there are any errors. keep it running while you try to connect and it should spit out any info about any devices trying to access that page.
