### ISSUE TITLE
Welcome to nginx

### ISSUE THREAD

**Issue by chevelle722** [mholgatem/ThermOS#12]
Just got a RaspberryPI and wanted to try your program; downloaded the lastest version of Rasbian, got you're program installed (successfully I believe lol?), but when I log into the Pi I just get this web page saying "Welcome to nginx" and that further configuration is needed. Any help would be much appreciated, thanks!

**Comment by chevelle722** [comment]
So I found that for some reason nginx is using the same port; used the systemctl and it gave me error 98, same socket used, then lsof -i:80 and it said nginx. So I stopped nginx and, used the "sudo python thermostat_Web.Py" command and was able to use the Web page no problem! Any advice as to how I can fix the nginx problem so I don't have to stop it everytime I restart the pi?

**Comment by chevelle722** [comment]
Sorry, found in a different thread to use the "sudo apt-get remove nginx" to delete it, which I did, but still get the "Welcome to Nginx" after I restart

**Comment by mholgatem** [comment]
ok, it should be fixed now. do this

```
cd ~
sudo rm -r ThermOS
git clone https://github.com/mholgatem/ThermOS 
cd ~/ThermOS  
sudo bash install.sh
```
