### ISSUE TITLE
Heat pump and heat strips

### ISSUE THREAD

**Issue by jeffwcollins** [mholgatem/ThermOS#14]
We emailed back and forth about six months ago about adding the option for the reversing valve and for heat strips, and was wondering about the potential for adding support for that.
If you are still interested, let me know if you need additional info on either, or if you need clarification on this request.

Thank you much!

**Comment by mholgatem** [comment]
yeah, I still plan on working on adding the option for the reversing valve, but I'm just swamped with work right now unfortunately.

**Comment by jeffwcollins** [comment]
Understood, and I do appreciate it.  Will continue to check back, or if I get time I can bash my way through and maybe submit a pull request.  Thanks again.

**Comment by mholgatem** [comment]
yeah, I have a neighbor that works on air conditioners for a living. When I get some time, I'd love to pick his brain and make this a 100% fully compatible thermostat.
