### ISSUE TITLE
Schedule - Can't delete schedule entry

### ISSUE THREAD

**Issue by DaBoss5132** [mholgatem/ThermOS#16]
Hi, love the project. One thing I noticed, at least on my build, there doesn't seem to be a way to delete a schedule entry... I can only create a new one or edit an existing one. So if I want to cancel a schedule entry, I have to change the entry to "date" and put it for a day sometime in the past. Am I missing something on my end perhaps? Keep up the great work!

**Comment by mholgatem** [comment]
There should be a trash can icon to the left of the entry. 
![delete](https://user-images.githubusercontent.com/6432985/37116218-da078780-220a-11e8-9aa4-d2ab56794288.jpg)

**Comment by DaBoss5132** [comment]
Thanks, I'll take a look. Neither the edit or trash icons are showing so
I'll dive into that on my side. Thanks!

**Comment by mholgatem** [comment]
hmm... that's strange. can you post a pic?

**Comment by mholgatem** [comment]
closing issue. Feel free to continue to comment here if you are still experiencing issues.
