### ISSUE TITLE
Different Weather api

### ISSUE THREAD

**Issue by Fishrider24** [mholgatem/ThermOS#21]
The dark sky api is no longer accepting new users. Is there a different api that will work with this?  Thank you!

**Comment by mholgatem** [comment]
Sorry. I don't have any plans to integrate a different API as I'm quite busy with work.

**Comment by Fishrider24** [comment]
Thanks for responding!  I am going to try and make open weather work. I will try to post an updated file if I figure it out.

**Comment by spiranis** [comment]
Hello Fishrider, would you mind sharing how you got this project to work as i followed the setup directions but when i try opening the site in the browser i get '502 Bad Gateway error'

Thanks

**Comment by Fishrider24** [comment]
I couldn't figure out how to switch it to open weather, so I am working on making my own thermostat.
