### ISSUE TITLE
How difficult would be be to have the AC function run a command from a file?

### ISSUE THREAD

**Issue by 10481** [mholgatem/ThermOS#5]
I don't know any python at all, but I'm going to try and learn. My question there though is to see if it would even be possible (in a relatively easy fashion) to change what the AC function does. I don't have forced air. I have a wall unit that I have plugged into a RF outlet like so [https://timleland.com/wireless-power-outlets/](url). So basically what I was hoping would be possible is that when the AC is supposed to turn on/off, it runs the `/var/www/rfoutlet/codesend “code number”` command instead.

It seems like it would be a good addition, especially in the southern hemisphere, where built in units are common.

**Comment by mholgatem** [comment]
it wouldn't be difficult at all. You would just need to implement it into the functions in the thermostat_daemon.py script. You would need to implement it into the "cool" and "powerdown" functions. 

probably something like:
`subprocess.call(("/var/www/rfoutlet/codesend", "code number"))`

That's just an educated guess though as I haven't tested it.

**Comment by 10481** [comment]
Well educated guess! I was a bit busy the last couple days, so I only got around to looking at it a bit today. It works great now. Thanks!
