### ISSUE TITLE
getting "sqlite3.OperationalError" and no wetherforcasts.

### ISSUE THREAD

**Issue by ssirkakriss** [mholgatem/ThermOS#9]
After a fresh install of 2017-09-07-raspbian-stretch-lite, and then installing ThermOS. The weather info seems broken. I did have this working well on my Rpi(B) from a previous version. The error in ThermOS logs is "Error while getting weather info: <class 'sqlite3.OperationalError'>"

Everything else seems fine except for the weather forecast info. I had thought I had missed a install step so I have tried doing a fresh install (os +ThermOS) several times and all the same error.

BTW, Thank you for this program. I'm just a hobbyist and ThemOS is a nice project for me.

**Comment by mholgatem** [comment]
ah, I added support for the new UV Index that is provided by the Dark Sky API but forgot to update the database to handle it. 
Type this in the command line and then reboot

`sqlite3 ~/ThermOS/logs/logs.db "ALTER TABLE hourlyWeather ADD COLUMN uvIndex NUMERIC"`

I will also update the installer script to automatically do this, in case you re-install in the future.
